// Journey Lessons Seed Data - 30 Day Course
// Run with: npx tsx prisma/journey-lessons.ts

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const WEEKS = {
  1: { name: 'Пробуждение', nameEn: 'Awakening' },
  2: { name: 'Закалка', nameEn: 'Tempering' },
  3: { name: 'Восхождение', nameEn: 'Ascension' },
  4: { name: 'Мастерство', nameEn: 'Mastery' },
}

const lessons = [
  // ============ НЕДЕЛЯ 1: ПРОБУЖДЕНИЕ ============
  {
    day: 1,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Добро пожаловать в LeakFixer',
    story: `Каждый великий путь начинается с первого шага. Сегодня ты начинаешь своё путешествие к лучшей версии себя. LeakFixer — это не просто приложение, это твой компас в мире личного развития. Давай настроим его под тебя!`,
    tasks: JSON.stringify([
      { id: 'profile_name', type: 'action', target: 'update_profile_name', description: 'Заполнить профиль (имя)', reward: 10, autoVerify: true },
      { id: 'weight_start', type: 'action', target: 'set_start_weight', description: 'Указать начальный вес', reward: 15, autoVerify: true },
      { id: 'weight_goal', type: 'action', target: 'set_target_weight', description: 'Установить целевой вес', reward: 15, autoVerify: true },
      { id: 'choose_goal', type: 'action', target: 'choose_main_goal', description: 'Выбрать главную цель', reward: 10, autoVerify: true },
    ]),
    quote: `"Путешествие в тысячу миль начинается с одного шага." — Лао-цзы`,
    tip: `Начни с честной оценки своего текущего состояния. Это твоя точка отсчёта.`,
    rewardXp: 50,
    achievement: 'first_steps',
    unlocks: JSON.stringify(['profile', 'mood', 'weight']),
  },
  {
    day: 2,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Ритуалы — основа изменений',
    story: `Успешные люди отличаются от остальных не тем, что они делают иногда, а тем, что они делают каждый день. Ритуалы — это маленькие действия, которые со временем создают огромные изменения. Сегодня ты создашь свою первую привычку.`,
    tasks: JSON.stringify([
      { id: 'view_rituals', type: 'check', target: 'view_rituals_screen', description: 'Посмотреть список ритуалов', reward: 5, autoVerify: true },
      { id: 'add_preset', type: 'action', target: 'add_ritual_preset', description: 'Подключить базовый пакет (12 ритуалов)', reward: 20, autoVerify: true },
      { id: 'complete_3', type: 'complete', target: 'complete_rituals', count: 3, description: 'Выполнить 3 ритуала', reward: 15, autoVerify: true },
    ]),
    quote: `"Мы — это то, что мы делаем постоянно. Совершенство, следовательно, не действие, а привычка." — Аристотель`,
    tip: `Начни с малого. Лучше делать 3 ритуала каждый день, чем 10 — раз в неделю.`,
    rewardXp: 40,
    achievement: 'first_ritual',
    unlocks: JSON.stringify(['rituals']),
  },
  {
    day: 3,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Настроение и энергия',
    story: `Настроение — это компас твоего внутреннего состояния. Когда ты научишься его отслеживать, ты поймёшь, что влияет на твою энергию и как её увеличивать. Это суперспособность, которую мы сегодня освоим.`,
    tasks: JSON.stringify([
      { id: 'mood_morning', type: 'action', target: 'update_mood', description: 'Обновить настроение (утро)', reward: 5, autoVerify: true },
      { id: 'mood_day', type: 'action', target: 'update_mood', description: 'Обновить настроение (день)', reward: 5, autoVerify: true },
      { id: 'mood_evening', type: 'action', target: 'update_mood', description: 'Обновить настроение (вечер)', reward: 5, autoVerify: true },
      { id: 'view_chart', type: 'check', target: 'view_mood_chart', description: 'Посмотреть график настроения', reward: 10, autoVerify: true },
    ]),
    quote: `"Энергия и настойчивость преобразуют все вещи." — Михай Чиксентмихайи`,
    tip: `Записывай настроение в одно и то же время — так ты увидишь более точную картину.`,
    rewardXp: 25,
    achievement: null,
    unlocks: null,
  },
  {
    day: 4,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Привычки — твои союзники',
    story: `Привычки отличаются от ритуалов тем, что они полностью твои. Ты создаёшь их сам, формируешь под свой образ жизни. Сегодня ты создашь свою первую привычку.`,
    tasks: JSON.stringify([
      { id: 'create_habit', type: 'create', target: 'create_habit', count: 1, description: 'Создать 1-2 привычки', reward: 15, autoVerify: true },
      { id: 'complete_habit', type: 'complete', target: 'complete_habit', description: 'Отметить выполнение привычки', reward: 10, autoVerify: true },
      { id: 'view_stats', type: 'check', target: 'view_habit_stats', description: 'Посмотреть статистику привычек', reward: 5, autoVerify: true },
    ]),
    quote: `"Привычка — вторая натура." — Цицерон`,
    tip: `Лучше всего работают привычки, привязанные к уже существующим действиям. "После чистки зубов я буду..."`,
    rewardXp: 30,
    achievement: 'habit_creator',
    unlocks: JSON.stringify(['habits']),
  },
  {
    day: 5,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Вода и питание',
    story: `Твоё тело — это храм, и то, что ты в него помещаешь, определяет твою энергию и здоровье. Сегодня мы начнём отслеживать топливо для твоего организма.`,
    tasks: JSON.stringify([
      { id: 'log_water', type: 'action', target: 'log_water', description: 'Записать выпитую воду', reward: 10, autoVerify: true },
      { id: 'add_food', type: 'action', target: 'add_food_entry', description: 'Добавить первый приём пищи', reward: 15, autoVerify: true },
      { id: 'view_summary', type: 'check', target: 'view_daily_summary', description: 'Посмотреть дневную сводку', reward: 5, autoVerify: true },
    ]),
    quote: `"Ты — то, что ты ешь." — Людвиг Фейербах`,
    tip: `Стакан воды утром запускает метаболизм. Попробуй!`,
    rewardXp: 30,
    achievement: null,
    unlocks: JSON.stringify(['water', 'food']),
  },
  {
    day: 6,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Дела и задачи',
    story: `Хаос в делах приводит к хаосу в голове. Сегодня ты научишься организовывать свои задачи так, чтобы ничего не упускать и успевать больше.`,
    tasks: JSON.stringify([
      { id: 'create_task', type: 'create', target: 'create_task', description: 'Создать первое дело', reward: 10, autoVerify: true },
      { id: 'complete_task', type: 'complete', target: 'complete_task', description: 'Выполнить его', reward: 15, autoVerify: true },
      { id: 'create_chain', type: 'create', target: 'create_chain', description: 'Создать проект (цепочку)', reward: 10, autoVerify: true },
      { id: 'add_chain_tasks', type: 'create', target: 'create_task_in_chain', count: 2, description: 'Добавить 2 дела в проект', reward: 10, autoVerify: true },
    ]),
    quote: `"Съешь лягушку с утра, и всё остальное покажется лёгким." — Брайан Трейси`,
    tip: `Начинай день с самой важной задачи. Это правило "съешь лягушку".`,
    rewardXp: 45,
    achievement: null,
    unlocks: JSON.stringify(['tasks', 'chains']),
  },
  {
    day: 7,
    week: 1,
    weekName: WEEKS[1].name,
    title: 'Недельный обзор',
    story: `Неделя позади. Время подвести итоги, отметить победы и понять, что можно улучшить. Еженедельный обзор — это ключ к постоянному росту.`,
    tasks: JSON.stringify([
      { id: 'view_stats', type: 'check', target: 'view_weekly_stats', description: 'Посмотреть статистику за неделю', reward: 10, autoVerify: true },
      { id: 'reflection', type: 'action', target: 'complete_reflection', description: 'Заполнить рефлексию недели', reward: 20, autoVerify: true },
      { id: 'adjust_goals', type: 'action', target: 'adjust_goals', description: 'Скорректировать цели', reward: 10, autoVerify: true },
    ]),
    quote: `"Не работай усерднее, работай умнее." — Аллен Ф. Мортенсон`,
    tip: `Выдели 15 минут в воскресенье на обзор недели. Это окупится сторицей.`,
    rewardXp: 100,
    achievement: 'week_one',
    unlocks: null,
  },

  // ============ НЕДЕЛЯ 2: ЗАКАЛКА ============
  {
    day: 8,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Здоровье — БАДы',
    story: `Иногда организму нужна дополнительная поддержка. Витамины и добавки могут восполнить дефициты и дать тебе больше энергии. Сегодня настроим твой режим приёма БАДов.`,
    tasks: JSON.stringify([
      { id: 'add_supplement', type: 'create', target: 'create_supplement', count: 1, description: 'Добавить 1-3 БАДа', reward: 15, autoVerify: true },
      { id: 'set_schedule', type: 'action', target: 'set_supplement_schedule', description: 'Настроить расписание приёма', reward: 10, autoVerify: true },
      { id: 'take_supplement', type: 'complete', target: 'complete_supplement_intake', description: 'Отметить приём', reward: 10, autoVerify: true },
    ]),
    quote: `"Здоровье — это не всё, но всё без здоровья — ничто." — Сократ`,
    tip: `Принимай БАДы в одно время с едой — так они лучше усваиваются.`,
    rewardXp: 35,
    achievement: null,
    unlocks: JSON.stringify(['supplements', 'measurements']),
  },
  {
    day: 9,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Тренировки — введение',
    story: `Движение — жизнь. Твоё тело создано для активности, и сегодня ты начнёшь свой тренировочный путь. Система GYM в LeakFixer построена на периодах и циклах — это профессиональный подход к тренировкам.`,
    tasks: JSON.stringify([
      { id: 'create_period', type: 'create', target: 'create_gym_period', description: 'Создать тренировочный период', reward: 15, autoVerify: true },
      { id: 'set_schedule', type: 'action', target: 'set_gym_schedule', description: 'Настроить расписание тренировок', reward: 10, autoVerify: true },
      { id: 'learn_cycles', type: 'check', target: 'view_gym_cycles', description: 'Ознакомиться с системой циклов', reward: 5, autoVerify: true },
    ]),
    quote: `"Твое тело может всё. Это мозг нужно убедить." — Неизвестный`,
    tip: `Начни с 3 тренировок в неделю. Этого достаточно для прогресса.`,
    rewardXp: 30,
    achievement: null,
    unlocks: JSON.stringify(['gym']),
  },
  {
    day: 10,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Тренировки — первая практика',
    story: `Теория без практики ничего не стоит. Сегодня ты проведёшь свою первую тренировку в LeakFixer. Не важно, какой уровень — важен сам факт начала.`,
    tasks: JSON.stringify([
      { id: 'create_workout', type: 'create', target: 'create_workout', description: 'Создать тренировку', reward: 15, autoVerify: true },
      { id: 'add_exercises', type: 'create', target: 'add_exercises', count: 3, description: 'Добавить 3-5 упражнений', reward: 15, autoVerify: true },
      { id: 'log_weights', type: 'action', target: 'log_exercise_weights', description: 'Указать веса/подходы/повторы', reward: 10, autoVerify: true },
      { id: 'complete_workout', type: 'complete', target: 'complete_workout', description: 'Завершить тренировку', reward: 20, autoVerify: true },
    ]),
    quote: `"Боль, которую ты чувствуешь сегодня, станет силой, которую ты почувствуешь завтра." — Неизвестный`,
    tip: `Не гонись за весами. Техника важнее.`,
    rewardXp: 60,
    achievement: 'first_workout',
    unlocks: null,
  },
  {
    day: 11,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Измерения тела',
    story: `Вес — это не единственный показатель прогресса. Объёмы тела дают более точную картину изменений. Сегодня добавим новые метрики.`,
    tasks: JSON.stringify([
      { id: 'add_measurements', type: 'action', target: 'add_body_measurements', description: 'Добавить замеры (талия, грудь и т.д.)', reward: 15, autoVerify: true },
      { id: 'view_history', type: 'check', target: 'view_weight_history', description: 'Посмотреть историю веса', reward: 5, autoVerify: true },
      { id: 'compare_goal', type: 'check', target: 'compare_with_goal', description: 'Сравнить с целью', reward: 5, autoVerify: true },
    ]),
    quote: `"То, что измеряется, улучшается." — Питер Друкер`,
    tip: `Замеряй тело в одно и то же время суток, лучше утром натощак.`,
    rewardXp: 25,
    achievement: null,
    unlocks: null,
  },
  {
    day: 12,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Продвинутые ритуалы',
    story: `Ты уже освоил базовые ритуалы. Теперь пора настроить их под свой ритм жизни. Группировка по времени суток, дни недели, напоминания — всё это сделает твою систему мощнее.`,
    tasks: JSON.stringify([
      { id: 'group_rituals', type: 'action', target: 'group_rituals_by_time', description: 'Сгруппировать ритуалы по времени', reward: 10, autoVerify: true },
      { id: 'set_days', type: 'action', target: 'set_ritual_days', description: 'Настроить дни недели для ритуалов', reward: 10, autoVerify: true },
      { id: 'set_reminders', type: 'action', target: 'set_ritual_reminders', description: 'Настроить напоминания', reward: 10, autoVerify: true },
    ]),
    quote: `"Дисциплина — это мост между целями и достижениями." — Джим Рон`,
    tip: `Утренние ритуалы задают тон всему дню. Начни с них.`,
    rewardXp: 30,
    achievement: null,
    unlocks: null,
  },
  {
    day: 13,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Настроение — глубже',
    story: `Ты уже неделю отслеживаешь настроение. Теперь время проанализировать паттерны. Что повышает твою энергию? Что её забирает?`,
    tasks: JSON.stringify([
      { id: 'mood_charts', type: 'check', target: 'view_mood_charts', description: 'Посмотреть графики настроения', reward: 10, autoVerify: true },
      { id: 'energy_charts', type: 'check', target: 'view_energy_charts', description: 'Посмотреть графики энергии', reward: 10, autoVerify: true },
      { id: 'find_patterns', type: 'action', target: 'note_mood_patterns', description: 'Найти корреляции', reward: 10, autoVerify: true },
    ]),
    quote: `"Самопознание — начало мудрости." — Сократ`,
    tip: `Обрати внимание на дни с высокой энергией — что их объединяет?`,
    rewardXp: 30,
    achievement: null,
    unlocks: null,
  },
  {
    day: 14,
    week: 2,
    weekName: WEEKS[2].name,
    title: 'Недельный обзор #2',
    story: `Вторая неделя завершена. Ты уже чувствуешь изменения? Сравним результаты с началом пути.`,
    tasks: JSON.stringify([
      { id: 'compare_weeks', type: 'check', target: 'compare_with_week_1', description: 'Сравнить статистику с неделей 1', reward: 15, autoVerify: true },
      { id: 'reflection', type: 'action', target: 'complete_reflection', description: 'Заполнить рефлексию', reward: 20, autoVerify: true },
      { id: 'note_wins', type: 'action', target: 'note_week_wins', description: 'Отметить достижения недели', reward: 15, autoVerify: true },
    ]),
    quote: `"Прогресс, а не совершенство." — Неизвестный`,
    tip: `Отметь даже маленькие победы. Они важнее, чем кажется.`,
    rewardXp: 150,
    achievement: 'week_two',
    unlocks: null,
  },

  // ============ НЕДЕЛЯ 3: ВОСХОЖДЕНИЕ ============
  {
    day: 15,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Направления жизни',
    story: `Куда ты движешься? Без компаса легко заблудиться. Направления жизни — это твои глобальные ориентиры, которые помогут принимать решения каждый день.`,
    tasks: JSON.stringify([
      { id: 'create_directions', type: 'create', target: 'create_direction', count: 2, description: 'Создать 2-3 направления', reward: 20, autoVerify: true },
      { id: 'describe_vision', type: 'action', target: 'describe_direction_vision', description: 'Описать видение каждого', reward: 15, autoVerify: true },
      { id: 'choose_colors', type: 'action', target: 'set_direction_colors', description: 'Выбрать цвета', reward: 5, autoVerify: true },
    ]),
    quote: `"Если у тебя нет цели, ты не попадёшь никуда." — Сенека`,
    tip: `Направления — это не конкретные цели, а векторы движения.`,
    rewardXp: 40,
    achievement: 'compass_set',
    unlocks: JSON.stringify(['directions', 'challenges']),
  },
  {
    day: 16,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Челленджи',
    story: `30-дневный челлендж — это мощный инструмент трансформации. Одна конкретная цель, один месяц, ежедневные действия. Сегодня ты создашь свой первый челлендж.`,
    tasks: JSON.stringify([
      { id: 'create_challenge', type: 'create', target: 'create_challenge', description: 'Создать персональный челлендж', reward: 20, autoVerify: true },
      { id: 'link_direction', type: 'action', target: 'link_challenge_to_direction', description: 'Привязать к направлению', reward: 10, autoVerify: true },
      { id: 'mark_first_day', type: 'complete', target: 'mark_challenge_day', description: 'Отметить первый день', reward: 10, autoVerify: true },
    ]),
    quote: `"Челлендж — это возможность стать лучше, а не доказать что-то другим." — Неизвестный`,
    tip: `Выбери челлендж, который реально выполнить. Лучше закончить простой, чем бросить сложный.`,
    rewardXp: 40,
    achievement: null,
    unlocks: null,
  },
  {
    day: 17,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Финансы — основы',
    story: `Деньги — это энергия. Когда ты контролируешь финансы, ты контролируешь часть своей жизни. Сегодня начнём наводить порядок в этой сфере.`,
    tasks: JSON.stringify([
      { id: 'create_accounts', type: 'create', target: 'create_account', count: 2, description: 'Создать 2-3 счёта', reward: 15, autoVerify: true },
      { id: 'create_categories', type: 'create', target: 'create_category', count: 3, description: 'Создать категории расходов', reward: 15, autoVerify: true },
      { id: 'add_transaction', type: 'create', target: 'create_transaction', description: 'Добавить первую транзакцию', reward: 10, autoVerify: true },
    ]),
    quote: `"Деньги — хороший слуга, но плохой хозяин." — П.Т. Барнум`,
    tip: `Начни с отслеживания всех расходов неделю — это откроет глаза.`,
    rewardXp: 40,
    achievement: null,
    unlocks: JSON.stringify(['finance']),
  },
  {
    day: 18,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Финансы — практика',
    story: `Осознание трат — первый шаг к финансовой свободе. Сегодня ты будешь записывать все расходы и увидишь, куда уходит твоя энергия.`,
    tasks: JSON.stringify([
      { id: 'track_expenses', type: 'action', target: 'track_all_expenses', description: 'Записывать расходы весь день', reward: 20, autoVerify: true },
      { id: 'view_summary', type: 'check', target: 'view_finance_summary', description: 'Посмотреть сводку дня', reward: 10, autoVerify: true },
      { id: 'find_issues', type: 'action', target: 'identify_problem_categories', description: 'Определить проблемные категории', reward: 10, autoVerify: true },
    ]),
    quote: `"Богатство — это не то, что ты зарабатываешь, а то, что ты сохраняешь." — Неизвестный`,
    tip: `Мелкие траты складываются в крупные суммы. Проверь подписки!`,
    rewardXp: 40,
    achievement: null,
    unlocks: null,
  },
  {
    day: 19,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Заметки',
    story: `Память ненадёжна. Заметки — это твой второй мозг. Сегодня мы настроим систему для хранения идей, мыслей и важной информации.`,
    tasks: JSON.stringify([
      { id: 'create_notes', type: 'create', target: 'create_note', count: 1, description: 'Создать 1-2 заметки', reward: 15, autoVerify: true },
      { id: 'set_zone', type: 'action', target: 'set_note_zone', description: 'Указать зону заметки', reward: 5, autoVerify: true },
      { id: 'link_task', type: 'action', target: 'link_note_to_task', description: 'Связать заметку с задачей', reward: 10, autoVerify: true },
    ]),
    quote: `"Самые важные мысли приходят в самые неподходящие моменты — запоминай их." — Неизвестный`,
    tip: `Используй заметки для дневника — это помогает обработать эмоции.`,
    rewardXp: 30,
    achievement: null,
    unlocks: JSON.stringify(['notes']),
  },
  {
    day: 20,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Контент и обучение',
    story: `Непрерывное обучение — ключ к росту. Книги, курсы, видео — всё это топливо для твоего развития. Давай организуем этот поток.`,
    tasks: JSON.stringify([
      { id: 'add_content', type: 'create', target: 'create_content_item', description: 'Добавить книгу/курс/видео', reward: 15, autoVerify: true },
      { id: 'track_progress', type: 'action', target: 'update_content_progress', description: 'Отметить прогресс', reward: 10, autoVerify: true },
      { id: 'plan_next', type: 'action', target: 'plan_content_continuation', description: 'Запланировать продолжение', reward: 10, autoVerify: true },
    ]),
    quote: `"Инвестиции в знания дают лучший процент." — Бенджамин Франклин`,
    tip: `Выдели 30 минут в день на обучение — это изменит твою жизнь.`,
    rewardXp: 35,
    achievement: null,
    unlocks: JSON.stringify(['content']),
  },
  {
    day: 21,
    week: 3,
    weekName: WEEKS[3].name,
    title: 'Недельный обзор #3',
    story: `Три недели позади. Ты уже освоил почти все функции приложения. Пора подвести итоги и подготовиться к финальному рывку.`,
    tasks: JSON.stringify([
      { id: 'all_charts', type: 'check', target: 'view_all_weekly_charts', description: 'Все графики за неделю', reward: 15, autoVerify: true },
      { id: 'finance_summary', type: 'check', target: 'view_finance_summary', description: 'Финансовый итог', reward: 10, autoVerify: true },
      { id: 'adjust_plans', type: 'action', target: 'adjust_monthly_plans', description: 'Корректировка планов', reward: 15, autoVerify: true },
      { id: 'reflection', type: 'action', target: 'complete_reflection', description: 'Рефлексия', reward: 20, autoVerify: true },
    ]),
    quote: `"Три недели формируют привычку. Ты на полпути к трансформации." — Неизвестный`,
    tip: `Оцени, какие функции приложения работают лучше всего для тебя.`,
    rewardXp: 200,
    achievement: 'week_three',
    unlocks: null,
  },

  // ============ НЕДЕЛЯ 4: МАСТЕРСТВО ============
  {
    day: 22,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Навыки и качества',
    story: `Какие навыки ты хочешь развить? Какими чертами характера хочешь обладать? Сегодня мы определим области для развития.`,
    tasks: JSON.stringify([
      { id: 'add_skills', type: 'create', target: 'create_skill', count: 2, description: 'Добавить 2-3 навыка', reward: 15, autoVerify: true },
      { id: 'add_traits', type: 'create', target: 'create_trait', count: 2, description: 'Добавить 2-3 черты характера', reward: 15, autoVerify: true },
      { id: 'rate_level', type: 'action', target: 'rate_current_level', description: 'Оценить текущий уровень', reward: 10, autoVerify: true },
    ]),
    quote: `"Мастерство — это не цель, а путь." — Роберт Грин`,
    tip: `Выбери навыки, которые помогут в твоих направлениях жизни.`,
    rewardXp: 40,
    achievement: null,
    unlocks: JSON.stringify(['skills', 'traits']),
  },
  {
    day: 23,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Продвинутые тренировки',
    story: `Ты уже провёл несколько тренировок. Теперь пора оптимизировать программу: шаблоны, прогрессия весов, анализ прогресса.`,
    tasks: JSON.stringify([
      { id: 'create_template', type: 'create', target: 'create_workout_template', description: 'Создать шаблон тренировки', reward: 15, autoVerify: true },
      { id: 'progression', type: 'action', target: 'increase_weights', description: 'Увеличить веса (прогрессия)', reward: 15, autoVerify: true },
      { id: 'analyze', type: 'check', target: 'analyze_workout_progress', description: 'Проанализировать прогресс', reward: 10, autoVerify: true },
    ]),
    quote: `"Прогрессия — ключ к росту. Делай немного больше каждый раз." — Неизвестный`,
    tip: `Увеличивай вес на 2.5-5% каждую неделю — это безопасный прогресс.`,
    rewardXp: 40,
    achievement: null,
    unlocks: null,
  },
  {
    day: 24,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Бадди — партнёры',
    story: `Вместе легче. Партнёр по отчётности — это человек, который поддержит и не даст сдаться. Сегодня найдём тебе бадди.`,
    tasks: JSON.stringify([
      { id: 'browse_users', type: 'check', target: 'view_users_list', description: 'Посмотреть пользователей', reward: 5, autoVerify: true },
      { id: 'send_request', type: 'action', target: 'send_buddy_request', description: 'Отправить запрос бадди', reward: 15, autoVerify: true },
      { id: 'interact', type: 'action', target: 'buddy_interaction', description: 'Начать взаимодействие', reward: 20, autoVerify: true },
    ]),
    quote: `"Если хочешь идти быстро — иди один. Если хочешь идти далеко — иди с другими." — Африканская пословица`,
    tip: `Бадди не обязательно должен быть другом. Это может быть незнакомец с похожими целями.`,
    rewardXp: 40,
    achievement: 'not_alone',
    unlocks: JSON.stringify(['buddies']),
  },
  {
    day: 25,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Экспорт в AI',
    story: `Все твои данные — это золото. AI может проанализировать их и дать персональные рекомендации. Сегодня мы используем эту суперспособность.`,
    tasks: JSON.stringify([
      { id: 'export_data', type: 'action', target: 'export_user_data', description: 'Экспортировать данные', reward: 15, autoVerify: true },
      { id: 'ai_analysis', type: 'action', target: 'send_to_ai', description: 'Отправить в AI-ассистента', reward: 15, autoVerify: true },
      { id: 'get_tips', type: 'action', target: 'receive_ai_recommendations', description: 'Получить рекомендации', reward: 10, autoVerify: true },
    ]),
    quote: `"Данные — это новая нефть. AI — это нефтеперерабатывающий завод." — Неизвестный`,
    tip: `Чем больше данных ты собрал, тем точнее будут рекомендации AI.`,
    rewardXp: 40,
    achievement: null,
    unlocks: JSON.stringify(['ai_export', 'advanced_features']),
  },
  {
    day: 26,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Автоматизация',
    story: `Успех в постоянстве. Напоминания помогут не пропускать важные действия. Настроим систему сигналов.`,
    tasks: JSON.stringify([
      { id: 'weight_reminder', type: 'action', target: 'set_weight_reminder', description: 'Настроить напоминания о весе', reward: 10, autoVerify: true },
      { id: 'ritual_reminders', type: 'action', target: 'set_ritual_reminders', description: 'Настроить напоминания о ритуалах', reward: 10, autoVerify: true },
      { id: 'weekly_reports', type: 'action', target: 'set_weekly_reports', description: 'Настроить еженедельные отчёты', reward: 10, autoVerify: true },
    ]),
    quote: `"Автоматизация освобождает время для того, что действительно важно." — Тим Феррис`,
    tip: `Не переусердствуй с напоминаниями — они могут начать раздражать.`,
    rewardXp: 30,
    achievement: null,
    unlocks: JSON.stringify(['reminders']),
  },
  {
    day: 27,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Продвинутая аналитика',
    story: `Почти месяц данных! Пора глубоко проанализировать все тренды и найти инсайты.`,
    tasks: JSON.stringify([
      { id: 'monthly_charts', type: 'check', target: 'view_monthly_charts', description: 'Все графики за месяц', reward: 20, autoVerify: true },
      { id: 'find_correlations', type: 'action', target: 'find_data_correlations', description: 'Найти корреляции', reward: 15, autoVerify: true },
      { id: 'identify_trends', type: 'action', target: 'identify_trends', description: 'Определить тренды', reward: 15, autoVerify: true },
    ]),
    quote: `"Данные говорят правду, если умеешь их слушать." — Нейт Сильвер`,
    tip: `Сравни начало и конец месяца — прогресс может удивить.`,
    rewardXp: 50,
    achievement: null,
    unlocks: null,
  },
  {
    day: 28,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Создание своих ритуалов',
    story: `Ты готов создавать уникальные ритуалы, которых нет в базовом пакете. Это твой личный код успеха.`,
    tasks: JSON.stringify([
      { id: 'create_custom', type: 'create', target: 'create_custom_ritual', count: 2, description: 'Создать 2-3 своих ритуала', reward: 20, autoVerify: true },
      { id: 'link_skills', type: 'action', target: 'link_rituals_to_skills', description: 'Связать с навыками', reward: 15, autoVerify: true },
      { id: 'set_schedule', type: 'action', target: 'set_custom_schedule', description: 'Настроить расписание', reward: 10, autoVerify: true },
    ]),
    quote: `"Твои ритуалы — это твоя подпись. Сделай их уникальными." — Неизвестный`,
    tip: `Экспериментируй! Не бойся пробовать новые ритуалы.`,
    rewardXp: 45,
    achievement: 'ritual_creator',
    unlocks: null,
  },
  {
    day: 29,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Настройка под себя',
    story: `Завтра финал. Сегодня — последняя настройка системы под твои нужды. Тема, организация, финальные штрихи.`,
    tasks: JSON.stringify([
      { id: 'set_theme', type: 'action', target: 'set_app_theme', description: 'Выбрать тему оформления', reward: 10, autoVerify: true },
      { id: 'check_reminders', type: 'action', target: 'verify_all_reminders', description: 'Проверить все напоминания', reward: 10, autoVerify: true },
      { id: 'organize', type: 'action', target: 'organize_data', description: 'Организовать данные', reward: 15, autoVerify: true },
    ]),
    quote: `"Система, которая работает на тебя, — это система, которую ты создал сам." — Неизвестный`,
    tip: `Подумай, что можно улучшить в твоей системе за следующий месяц.`,
    rewardXp: 35,
    achievement: null,
    unlocks: null,
  },
  {
    day: 30,
    week: 4,
    weekName: WEEKS[4].name,
    title: 'Финал и новые горизонты',
    story: `🎉 Поздравляем! Ты прошёл весь курс LeakFixer Journey! 30 дней назад ты начал путь к лучшей версии себя. Сегодня мы подведём итоги и наметим новые горизонты.`,
    tasks: JSON.stringify([
      { id: 'view_achievements', type: 'check', target: 'view_all_achievements', description: 'Посмотреть все достижения', reward: 20, autoVerify: true },
      { id: 'full_report', type: 'check', target: 'view_full_report', description: 'Полный отчёт по всем сферам', reward: 30, autoVerify: true },
      { id: 'plan_next', type: 'action', target: 'plan_next_month', description: 'Написать планы на следующий месяц', reward: 25, autoVerify: true },
      { id: 'complete', type: 'action', target: 'complete_journey', description: 'Отметить завершение курса', reward: 50, autoVerify: true },
    ]),
    quote: `"Конец — это новое начало. Твоё путешествие только начинается." — Неизвестный`,
    tip: `Ты теперь мастер LeakFixer! Используй эти знания мудро.`,
    rewardXp: 500,
    achievement: 'journey_master',
    unlocks: null,
  },
]

async function main() {
  console.log('🌱 Seeding Journey Lessons...')

  // Delete existing lessons
  await prisma.journeyLesson.deleteMany({})
  console.log('🗑️ Deleted existing lessons')

  // Insert new lessons
  for (const lesson of lessons) {
    await prisma.journeyLesson.create({
      data: lesson,
    })
    console.log(`✅ Created lesson for day ${lesson.day}: ${lesson.title}`)
  }

  console.log('🎉 Seeding complete!')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
