import { NextResponse } from 'next/server'

// Hardcoded challenge template catalog (~10 entries)
const TEMPLATES = [
  {
    id:          'ritual_21',
    name:        '21 день ритуалов',
    emoji:       '🔥',
    type:        'ritual',
    zone:        'health',
    category:    'lifestyle',
    duration:    21,
    description: 'Выполняй все ритуалы 21 день подряд. Именно столько нужно чтобы привычка закрепилась.',
    config:      {},
  },
  {
    id:          'gym_30',
    name:        '30 дней зала',
    emoji:       '💪',
    type:        'ritual',
    zone:        'health',
    category:    'health',
    duration:    30,
    description: '30 тренировок за 30 дней. Не обязательно каждый день — главное не пропускать больше 2 дней подряд.',
    config:      { targetCount: 30, periodDays: 30 },
  },
  {
    id:          'no_junk_14',
    name:        '14 дней без срывов',
    emoji:       '🥗',
    type:        'ritual',
    zone:        'health',
    category:    'health',
    duration:    14,
    description: '14 дней без плохих приёмов пищи. Один срыв — не конец, но старайся держаться.',
    config:      {},
  },
  {
    id:          'water_7',
    name:        '7 дней нормы воды',
    emoji:       '💧',
    type:        'custom',
    zone:        'health',
    category:    'health',
    duration:    7,
    description: '7 дней выполнять дневную норму воды. Просто и эффективно.',
    config:      { targetCount: 7, periodDays: 7, actionType: 'days' },
  },
  {
    id:          'poker_21',
    name:        '21 день дисциплины',
    emoji:       '♠️',
    type:        'custom',
    zone:        'poker',
    category:    'money',
    duration:    21,
    description: '21 день дисциплины за покерным столом. Фиксируй каждую сессию и принимай только EV+ решения.',
    config:      { targetCount: 21, periodDays: 21, actionType: 'days' },
  },
  {
    id:          'savings_30',
    name:        'Месяц сбережений',
    emoji:       '💰',
    type:        'custom',
    zone:        'savings',
    category:    'money',
    duration:    30,
    description: 'Откладывай каждый день и контролируй бюджет 30 дней. Строй финансовую подушку.',
    config:      { targetCount: 30, periodDays: 30, actionType: 'days' },
  },
  {
    id:          'early_rise_7',
    name:        '7 дней ранний подъём',
    emoji:       '🌅',
    type:        'ritual',
    zone:        'life',
    category:    'lifestyle',
    duration:    7,
    description: 'Вставай до 7:00 утра 7 дней подряд. Утро задаёт тон всему дню.',
    config:      {},
  },
  {
    id:          'leakfixer_30',
    name:        '30 дней LeakFixer',
    emoji:       '🔧',
    type:        'custom',
    zone:        'leakfixer',
    category:    'lifestyle',
    duration:    30,
    description: 'Работай над своими ликами 30 дней. Ежедневные чекапы, анализ и маленькие улучшения.',
    config:      { targetCount: 30, periodDays: 30, actionType: 'days' },
  },
  {
    id:          'mindful_14',
    name:        '14 дней осознанности',
    emoji:       '🧘',
    type:        'ritual',
    zone:        'life',
    category:    'lifestyle',
    duration:    14,
    description: '14 дней медитации или дыхательных упражнений. 10 минут в день меняют всё.',
    config:      {},
  },
  {
    id:          'no_spend_7',
    name:        '7 дней без лишних трат',
    emoji:       '🚫',
    type:        'custom',
    zone:        'savings',
    category:    'money',
    duration:    7,
    description: 'Неделя без импульсивных покупок. Только необходимое.',
    config:      { targetCount: 7, periodDays: 7, actionType: 'days' },
  },
]

// GET /api/challenges/templates
export async function GET() {
  return NextResponse.json({ success: true, templates: TEMPLATES })
}
