import { RitualPreset, CatalogRitual, AttributeKey } from './data'

// Базовый пресет "Выход из болота"
export const SWAMP_ESCAPE_PRESET: RitualPreset = {
  id: 'swamp_escape',
  name: 'Базовый пакет для выхода из болота',
  description: '12 ритуалов для тех, кто хочет начать двигаться. Минимум, который даёт максимум.',
  icon: '🏃',
  rituals: [
    {
      id: 'preset_water',
      title: 'Стакан воды утром',
      category: 'health',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'morning',
      goalShort: 'Запустить организм после сна',
      description: '0,5 л воды сразу после пробуждения. Можно добавить лимон.',
      attributes: ['health', 'will'] as AttributeKey[],
      icon: '💧',
    },
    {
      id: 'preset_exercise',
      title: 'Зарядка / разминка',
      category: 'health',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'morning',
      goalShort: 'Разбудить тело и зарядиться энергией',
      description: 'Короткий видео-комплекс, 10-20 минут. Можно найти на YouTube.',
      attributes: ['health', 'will'] as AttributeKey[],
      icon: '🏋️',
    },
    {
      id: 'preset_shower',
      title: 'Контрастный душ',
      category: 'health',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'morning',
      goalShort: 'Закалить организм и взбодриться',
      description: 'По 30 секунд горячая/холодная, начать и закончить холодной. Минимум 3 цикла.',
      attributes: ['health', 'will'] as AttributeKey[],
      icon: '🚿',
    },
    {
      id: 'preset_breathing',
      title: 'Дыхательные практики',
      category: 'mind',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'morning',
      goalShort: 'Успокоить ум и насытить клетки кислородом',
      description: '1 сессия по видео (5-15 минут). Метод Вима Хофа или просто глубокое дыхание.',
      attributes: ['mind', 'health'] as AttributeKey[],
      icon: '🌬️',
    },
    {
      id: 'preset_goals',
      title: 'Цели (метод Брайана Трейси)',
      category: 'productivity',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'morning',
      goalShort: 'Настроить фокус на важное',
      description: 'Утренний список 10 целей. Выбери главную и работай над ней первой.',
      attributes: ['mind', 'will'] as AttributeKey[],
      icon: '🎯',
    },
    {
      id: 'preset_plan',
      title: 'Временной план дня',
      category: 'productivity',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'morning',
      goalShort: 'Структурировать день заранее',
      description: 'Набросок 3-5 блоков дня. Когда что делаешь — примерное расписание.',
      attributes: ['mind', 'will'] as AttributeKey[],
      icon: '📅',
    },
    {
      id: 'preset_walk',
      title: 'Прогулка',
      category: 'health',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'any',
      goalShort: 'Движение — это жизнь',
      description: 'Минимум 5 км в день. Идеально 5-10 км. Можно разделить на несколько выходов.',
      attributes: ['health', 'will'] as AttributeKey[],
      icon: '🚶',
    },
    {
      id: 'preset_homeworkout',
      title: 'Домашняя тренировка',
      category: 'health',
      days: [1, 3, 5],
      timeWindow: 'evening',
      goalShort: 'Поддерживать тонус мышц',
      description: 'Круг: отжимания, приседания, икры, трицепс, пресс. 3-4 круга по 10-15 повторений.',
      attributes: ['health', 'will'] as AttributeKey[],
      icon: '💪',
    },
    {
      id: 'preset_meditation',
      title: 'Медитация',
      category: 'mind',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'evening',
      goalShort: 'Успокоить ум перед сном',
      description: '10-15 минут. Можно использовать приложение или просто сидеть в тишине.',
      attributes: ['mind', 'will'] as AttributeKey[],
      icon: '🧘',
    },
    {
      id: 'preset_learning',
      title: 'Изучение курса',
      category: 'learning',
      days: [1, 2, 3, 4, 5],
      timeWindow: 'day',
      goalShort: 'Двигаться в обучении каждый день',
      description: '1 урок или 20-30 минут изучения. Важно постоянство, не объём.',
      attributes: ['mind'] as AttributeKey[],
      icon: '📖',
    },
    {
      id: 'preset_reading',
      title: 'Чтение',
      category: 'learning',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'evening',
      goalShort: 'Расширять кругозор',
      description: 'Минимум 20 страниц. Книги по саморазвитию или профессии.',
      attributes: ['mind'] as AttributeKey[],
      icon: '📚',
    },
    {
      id: 'preset_evening_plan',
      title: 'Вечернее планирование',
      category: 'productivity',
      days: [1, 2, 3, 4, 5, 6, 7],
      timeWindow: 'evening',
      goalShort: 'Подготовиться к завтрашнему дню',
      description: 'Подвести итоги дня и составить 3-5 задач на завтра.',
      attributes: ['mind', 'will'] as AttributeKey[],
      icon: '📝',
    },
  ],
}

// Каталог готовых ритуалов
export const RITUAL_CATALOG: CatalogRitual[] = [
  // Здоровье
  {
    id: 'cat_water_2l',
    title: 'Пить 2л воды в день',
    category: 'health',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'any',
    goalShort: 'Поддерживать водный баланс',
    attributes: ['health'] as AttributeKey[],
    icon: '💧',
  },
  {
    id: 'cat_sleep_7h',
    title: 'Спать 7-8 часов',
    category: 'health',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'evening',
    goalShort: 'Восстанавливать силы качественным сном',
    attributes: ['health', 'mind'] as AttributeKey[],
    icon: '😴',
  },
  {
    id: 'cat_no_sugar',
    title: 'Без сахара',
    category: 'health',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'any',
    goalShort: 'Снизить воспаления и улучшить энергию',
    description: 'Исключить добавленный сахар из рациона.',
    attributes: ['health', 'will'] as AttributeKey[],
    icon: '🚫',
  },
  {
    id: 'cat_stretching',
    title: 'Растяжка',
    category: 'health',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'morning',
    goalShort: 'Сохранять гибкость тела',
    attributes: ['health'] as AttributeKey[],
    icon: '🧘',
  },
  
  // Психика
  {
    id: 'cat_gratitude',
    title: 'Благодарность',
    category: 'mind',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'evening',
    goalShort: 'Фокус на хорошем',
    description: 'Записать 3 вещи, за которые благодарен сегодня.',
    attributes: ['mind'] as AttributeKey[],
    icon: '🙏',
  },
  {
    id: 'cat_journal',
    title: 'Дневник',
    category: 'mind',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'evening',
    goalShort: 'Отслеживать мысли и прогресс',
    attributes: ['mind'] as AttributeKey[],
    icon: '📓',
  },
  {
    id: 'cat_no_phone_morning',
    title: 'Без телефона утром',
    category: 'mind',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'morning',
    goalShort: 'Сохранять ясность ума',
    description: 'Первые 30-60 минут после пробуждения без экранов.',
    attributes: ['mind', 'will'] as AttributeKey[],
    icon: '📵',
  },
  
  // Обучение
  {
    id: 'cat_english',
    title: 'Английский',
    category: 'learning',
    days: [1, 2, 3, 4, 5],
    timeWindow: 'day',
    goalShort: 'Улучшать язык каждый день',
    description: '15-30 минут практики: слова, грамматика, прослушивание.',
    attributes: ['mind'] as AttributeKey[],
    icon: '🇬🇧',
  },
  {
    id: 'cat_podcast',
    title: 'Обучающий подкаст',
    category: 'learning',
    days: [1, 2, 3, 4, 5],
    timeWindow: 'day',
    goalShort: 'Узнавать новое в формате аудио',
    attributes: ['mind'] as AttributeKey[],
    icon: '🎧',
  },
  
  // Продуктивность
  {
    id: 'cat_deepwork',
    title: 'Глубокая работа',
    category: 'productivity',
    days: [1, 2, 3, 4, 5],
    timeWindow: 'day',
    goalShort: 'Фокус на важном без отвлечений',
    description: '1-2 часа концентрированной работы без телефона и соцсетей.',
    attributes: ['will', 'mind'] as AttributeKey[],
    icon: '🎯',
  },
  {
    id: 'cat_inbox_zero',
    title: 'Inbox Zero',
    category: 'productivity',
    days: [1, 2, 3, 4, 5],
    timeWindow: 'evening',
    goalShort: 'Не копить незакрытые дела',
    description: 'Разобрать почту и сообщения до конца дня.',
    attributes: ['will'] as AttributeKey[],
    icon: '📧',
  },
  
  // Деньги
  {
    id: 'cat_track_expenses',
    title: 'Учитывать расходы',
    category: 'money',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'evening',
    goalShort: 'Видеть, куда уходят деньги',
    attributes: ['will'] as AttributeKey[],
    icon: '📊',
  },
  {
    id: 'cat_no_impulse',
    title: 'Без импульсивных покупок',
    category: 'money',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'any',
    goalShort: 'Контролировать траты',
    description: '24 часа на обдумывание любой незапланированной покупки.',
    attributes: ['will'] as AttributeKey[],
    icon: '🛒',
  },
  
  // Отношения
  {
    id: 'cat_connect',
    title: 'Связаться с близкими',
    category: 'relationships',
    days: [1, 3, 5],
    timeWindow: 'evening',
    goalShort: 'Поддерживать связи',
    description: 'Позвонить или написать близкому человеку.',
    attributes: ['mind'] as AttributeKey[],
    icon: '❤️',
  },
  {
    id: 'cat_compliment',
    title: 'Искренний комплимент',
    category: 'relationships',
    days: [1, 2, 3, 4, 5],
    timeWindow: 'day',
    goalShort: 'Дарить позитив окружающим',
    attributes: ['mind'] as AttributeKey[],
    icon: '💬',
  },
  
  // Воля
  {
    id: 'cat_cold_shower',
    title: 'Холодный душ',
    category: 'health',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'morning',
    goalShort: 'Закалить волю и тело',
    description: '30-60 секунд холодной воды. Начать постепенно.',
    attributes: ['health', 'will'] as AttributeKey[],
    icon: '❄️',
  },
  {
    id: 'cat_no_socials',
    title: 'Без соцсетей',
    category: 'productivity',
    days: [1, 2, 3, 4, 5, 6, 7],
    timeWindow: 'any',
    goalShort: 'Освободить время и внимание',
    description: 'Ограничить соцсети до 30 минут в день.',
    attributes: ['will', 'mind'] as AttributeKey[],
    icon: '📵',
  },
]

// Get all presets
export function getPresets(): RitualPreset[] {
  return [SWAMP_ESCAPE_PRESET]
}

// Get preset by ID
export function getPresetById(id: string): RitualPreset | undefined {
  return getPresets().find(p => p.id === id)
}

// Get catalog rituals
export function getCatalogRituals(): CatalogRitual[] {
  return RITUAL_CATALOG
}
